steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/zentrity-351920/backend-zentrity/production:1.1', '.' ]
images: ['us-central1-docker.pkg.dev/zentrity-351920/backend-zentrity/production']

#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'us-central1-docker.pkg.dev/zentrity-351920/backend-zentrity/production:1.0', '.']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'us-central1-docker.pkg.dev/zentrity-351920/backend-zentrity/production']